# a=input("Enter a name")
# b=input("Enetr you age")
# b=int(b)
# print(a)
# print(b)
# print(type(b))
a=input("Enter a number")
a=int(a)
b=input("Enetr a number")
b=int(b)
print("additon of two number",(a+b))